### ISSUE TITLE
Mô hình ERD

### ISSUE THREAD

**Issue by phunghx** [NguyenVanThang17110230/KLTN_KTDV#1]
@NguyenVanThang17110230  @vanha1108 
1. User và report_owner khác nhau thế nào?
2. 1 user có nhiều report và 1 report (đề tài) có thể được làm bởi nhiều user
3. Điểm không cần tách thành 1 bảng riêng, điểm là 1 thuộc tính của report

**Comment by vanha1108** [comment]
@phunghx 
1. User là người dùng của hệ thống còn report_owner là người sở hữu của report được upload lên hệ thống (Cụ thể là giáo viên hướng dẫn và các sinh viên thực hiện report đó)
2. Nhóm em đang hiểu theo hướng hệ thống này chỉ cho giáo viên sử dụng và 1 admin quản trị hệ thống. Sinh viên không được phép truy cập vào hệ thống này.
3. Nhóm em sẽ update vấn đề này.

**Comment by phunghx** [comment]
Hệ thống này cho phép sinh viên được upload đề tài lên để kiểm tra thông tin đạo văn
